const List<String> locations = [
  "Beograd",
  "Novi Sad",
  "Niš",
  "Kragujevac",
  "Subotica",
  "Zrenjanin",
  "Pančevo",
  "Čačak",
  "Kraljevo",
  "Leskovac",
  "Smederevo",
  "Kruševac",
  "Valjevo",
  "Vranje",
  "Šabac",
  "Užice",
  "Zaječar",
  "Požarevac",
  "Sombor",
  "Jagodina",
];
const List<String> categories = [
  "Водоинсталатер",
  "Електричар",
  "Молер",
  "Столар",
  "Аутомеханичар",
  "Зидар",
  "Керамичар",
  "Тесар",
  "Бравар",
  "Заваривач",
  "Гипсар",
  "Паркетар",
  "Фарбар",
  "Мајстор за клима уређаје",
  "Монтер ПВЦ столарије",
];
